exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('companies').del()
    .then(() => {
      // Inserts seed entries
      return knex('companies').insert([
        {id: 1, company_name: 'Walmart', zip_code: 72716, times_rated: 0, total_rating: 0},
        {id: 2, company_name: 'Exxon Mobil', zip_code: 75039, times_rated: 0, total_rating: 0},
        {id: 3, company_name: 'Chevron', zip_code: 94583, times_rated: 0, total_rating: 0},
        {id: 4, company_name: 'Berkshire Hathaway', zip_code: 68131, times_rated: 0, total_rating: 0},
        {id: 5, company_name: 'Apple', zip_code: 95014, times_rated: 0, total_rating: 0},
        {id: 6, company_name: 'General Motors', zip_code: 48265, times_rated: 0, total_rating: 0},
        {id: 7, company_name: 'Phillips 66', zip_code: 77042, times_rated: 0, total_rating: 0},
        {id: 8, company_name: 'General Electric', zip_code: 6828, times_rated: 0, total_rating: 0},
        {id: 9, company_name: 'Ford Motor', zip_code: 48126, times_rated: 0, total_rating: 0},
        {id: 10, company_name: 'CVS Health', zip_code: 2895, times_rated: 0, total_rating: 0},
        {id: 11, company_name: 'McKesson', zip_code: 94104, times_rated: 0, total_rating: 0},
        {id: 12, company_name: 'AT&T', zip_code: 75202, times_rated: 0, total_rating: 0},
        {id: 13, company_name: 'Valero Energy', zip_code: 78249, times_rated: 0, total_rating: 0},
        {id: 14, company_name: 'UnitedHealth Group', zip_code: 55343, times_rated: 0, total_rating: 0},
        {id: 15, company_name: 'Verizon', zip_code: 10007, times_rated: 0, total_rating: 0},
        {id: 16, company_name: 'AmerisourceBergen', zip_code: 19087, times_rated: 0, total_rating: 0},
        {id: 17, company_name: 'Fannie Mae', zip_code: 20016, times_rated: 0, total_rating: 0},
        {id: 18, company_name: 'Costco', zip_code: 98027, times_rated: 0, total_rating: 0},
        {id: 19, company_name: 'HP', zip_code: 94304, times_rated: 0, total_rating: 0},
        {id: 20, company_name: 'Kroger', zip_code: 45202, times_rated: 0, total_rating: 0},
        {id: 21, company_name: 'JP Morgan Chase', zip_code: 10017, times_rated: 0, total_rating: 0},
        {id: 22, company_name: 'Express Scripts Holding', zip_code: 63121, times_rated: 0, total_rating: 0},
        {id: 23, company_name: 'Bank of America Corp.', zip_code: 28255, times_rated: 0, total_rating: 0},
        {id: 24, company_name: 'IBM', zip_code: 10504, times_rated: 0, total_rating: 0},
        {id: 25, company_name: 'Marathon Petroleum', zip_code: 45840, times_rated: 0, total_rating: 0},
        {id: 26, company_name: 'Cardinal Health', zip_code: 43017, times_rated: 0, total_rating: 0},
        {id: 27, company_name: 'Boeing', zip_code: 60606, times_rated: 0, total_rating: 0},
        {id: 28, company_name: 'Citigroup', zip_code: 10022, times_rated: 0, total_rating: 0},
        {id: 29, company_name: 'Amazon.com', zip_code: 98109, times_rated: 0, total_rating: 0},
        {id: 30, company_name: 'Wells Fargo', zip_code: 94163, times_rated: 0, total_rating: 0},
        {id: 31, company_name: 'Microsoft', zip_code: 98052, times_rated: 0, total_rating: 0},
        {id: 32, company_name: 'Procter & Gamble', zip_code: 45202, times_rated: 0, total_rating: 0},
        {id: 33, company_name: 'Home Depot', zip_code: 30339, times_rated: 0, total_rating: 0},
        {id: 34, company_name: 'Archer Daniels Midland', zip_code: 62526, times_rated: 0, total_rating: 0},
        {id: 35, company_name: 'Walgreens', zip_code: 60015, times_rated: 0, total_rating: 0},
        {id: 36, company_name: 'Target', zip_code: 55403, times_rated: 0, total_rating: 0},
        {id: 37, company_name: 'Johnson & Johnson', zip_code: 8933, times_rated: 0, total_rating: 0},
        {id: 38, company_name: 'Anthem', zip_code: 46204, times_rated: 0, total_rating: 0},
        {id: 39, company_name: 'MetLife', zip_code: 10166, times_rated: 0, total_rating: 0},
        {id: 40, company_name: 'Google', zip_code: 94043, times_rated: 0, total_rating: 0},
        {id: 41, company_name: 'State Farm Insurance Cos.', zip_code: 61710, times_rated: 0, total_rating: 0},
        {id: 42, company_name: 'Freddie Mac', zip_code: 22102, times_rated: 0, total_rating: 0},
        {id: 43, company_name: 'Comcast', zip_code: 19103, times_rated: 0, total_rating: 0},
        {id: 44, company_name: 'PepsiCo', zip_code: 10577, times_rated: 0, total_rating: 0},
        {id: 45, company_name: 'United Technologies', zip_code: 6101, times_rated: 0, total_rating: 0},
        {id: 46, company_name: 'AIG', zip_code: 10038, times_rated: 0, total_rating: 0},
        {id: 47, company_name: 'UPS', zip_code: 30328, times_rated: 0, total_rating: 0},
        {id: 48, company_name: 'Dow Chemical', zip_code: 48674, times_rated: 0, total_rating: 0},
        {id: 49, company_name: 'Aetna', zip_code: 6156, times_rated: 0, total_rating: 0},
        {id: 50, company_name: "Lowe's", zip_code: 28117, times_rated: 0, total_rating: 0},
        {id: 51, company_name: 'ConocoPhillips', zip_code: 77079, times_rated: 0, total_rating: 0},
        {id: 52, company_name: 'Intel', zip_code: 95054, times_rated: 0, total_rating: 0},
        {id: 53, company_name: 'Energy Transfer Equity', zip_code: 75219, times_rated: 0, total_rating: 0},
        {id: 54, company_name: 'Caterpillar', zip_code: 61629, times_rated: 0, total_rating: 0},
        {id: 55, company_name: 'Prudential Financial', zip_code: 7102, times_rated: 0, total_rating: 0},
        {id: 56, company_name: 'Pfizer', zip_code: 10017, times_rated: 0, total_rating: 0},
        {id: 57, company_name: 'Disney', zip_code: 91521, times_rated: 0, total_rating: 0},
        {id: 58, company_name: 'Humana', zip_code: 40202, times_rated: 0, total_rating: 0},
        {id: 59, company_name: 'Enterprise Products Partners', zip_code: 77002, times_rated: 0, total_rating: 0},
        {id: 60, company_name: 'Cisco Systems', zip_code: 95134, times_rated: 0, total_rating: 0},
        {id: 61, company_name: 'Sysco', zip_code: 77077, times_rated: 0, total_rating: 0},
        {id: 62, company_name: 'Ingram Micro', zip_code: 92705, times_rated: 0, total_rating: 0},
        {id: 63, company_name: 'Coca-Cola', zip_code: 30313, times_rated: 0, total_rating: 0},
        {id: 64, company_name: 'Lockheed Martin', zip_code: 20817, times_rated: 0, total_rating: 0},
        {id: 65, company_name: 'FedEx', zip_code: 38120, times_rated: 0, total_rating: 0},
        {id: 66, company_name: 'Johnson Controls', zip_code: 53209, times_rated: 0, total_rating: 0},
        {id: 67, company_name: 'Plains GP Holdings', zip_code: 77002, times_rated: 0, total_rating: 0},
        {id: 68, company_name: 'World Fuel Services', zip_code: 33178, times_rated: 0, total_rating: 0},
        {id: 69, company_name: 'CHS', zip_code: 55077, times_rated: 0, total_rating: 0},
        {id: 70, company_name: 'American Airlines Group', zip_code: 76155, times_rated: 0, total_rating: 0},
        {id: 71, company_name: 'Merck', zip_code: 8889, times_rated: 0, total_rating: 0},
        {id: 72, company_name: 'Best Buy', zip_code: 55423, times_rated: 0, total_rating: 0},
        {id: 73, company_name: 'Delta Air Lines', zip_code: 30354, times_rated: 0, total_rating: 0},
        {id: 74, company_name: 'Honeywell International', zip_code: 7962, times_rated: 0, total_rating: 0},
        {id: 75, company_name: 'HCA Holdings', zip_code: 37203, times_rated: 0, total_rating: 0},
        {id: 76, company_name: 'Goldman Sachs Group', zip_code: 10282, times_rated: 0, total_rating: 0},
        {id: 77, company_name: 'Tesoro', zip_code: 78259, times_rated: 0, total_rating: 0},
        {id: 78, company_name: 'Liberty Mutual Insurance Group', zip_code: 2116, times_rated: 0, total_rating: 0},
        {id: 79, company_name: 'United Continental Holdings', zip_code: 60606, times_rated: 0, total_rating: 0},
        {id: 80, company_name: 'New York Life Insurance', zip_code: 10010, times_rated: 0, total_rating: 0},
        {id: 81, company_name: 'Oracle', zip_code: 94065, times_rated: 0, total_rating: 0},
        {id: 82, company_name: 'Morgan Stanley', zip_code: 10036, times_rated: 0, total_rating: 0},
        {id: 83, company_name: 'Tyson Foods', zip_code: 72762, times_rated: 0, total_rating: 0},
        {id: 84, company_name: 'Safeway', zip_code: 94588, times_rated: 0, total_rating: 0},
        {id: 85, company_name: 'Nationwide', zip_code: 43215, times_rated: 0, total_rating: 0},
        {id: 86, company_name: 'Deere', zip_code: 61265, times_rated: 0, total_rating: 0},
        {id: 87, company_name: 'DuPont', zip_code: 19898, times_rated: 0, total_rating: 0},
        {id: 88, company_name: 'American Express', zip_code: 10285, times_rated: 0, total_rating: 0},
        {id: 89, company_name: 'Allstate', zip_code: 60062, times_rated: 0, total_rating: 0},
        {id: 90, company_name: 'Cigna', zip_code: 6002, times_rated: 0, total_rating: 0},
        {id: 91, company_name: 'Mondelez International', zip_code: 60015, times_rated: 0, total_rating: 0},
        {id: 92, company_name: 'TIAA-CREF', zip_code: 10017, times_rated: 0, total_rating: 0},
        {id: 93, company_name: 'INTL FCStone', zip_code: 10017, times_rated: 0, total_rating: 0},
        {id: 94, company_name: 'Massachusetts Mutual Life Insur', zip_code: 1111, times_rated: 0, total_rating: 0},
        {id: 95, company_name: 'DirecTV', zip_code: 90245, times_rated: 0, total_rating: 0},
        {id: 96, company_name: 'Halliburton', zip_code: 77032, times_rated: 0, total_rating: 0},
        {id: 97, company_name: 'Twenty-First Century Fox', zip_code: 10036, times_rated: 0, total_rating: 0},
        {id: 98, company_name: '3M', zip_code: 55144, times_rated: 0, total_rating: 0},
        {id: 99, company_name: 'Sears Holdings', zip_code: 60179, times_rated: 0, total_rating: 0},
        {id: 100, company_name: 'General Dynamics', zip_code: 22042, times_rated: 0, total_rating: 0}
      ])
    })
}
